repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v2.21.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov
      - id: terraform_docs
      - id: terraform_providers_lock
      - id: terraform_validate
