name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      mongodb_atlas_api_pub_key: ${{ secrets.mongodb_atlas_api_pub_key }}
      mongodb_atlas_api_pri_key: ${{ secrets.mongodb_atlas_api_pri_key }}
      mongodb_atlas_org_id: ${{ secrets.mongodb_atlas_org_id }}
      aws_account_id: ${{ secrets.aws_account_id }}
      aws_access_key: ${{ secrets.aws_access_key }}
      aws_secret_key: ${{ secrets.aws_secret_key }}
      datadog_api_key: ${{ secrets.datadog_api_key }}
      mongodb_atlas_accesslistip: ${{ env.mongodb_atlas_accesslistip }}
      aws_region: ${{ env.aws_region }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
