name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Terraform Init
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Go Tests
      run: go test ../../tests/main_test.go

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
