name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        #run: terraform init
        env:
          mongodb_atlas_api_pub_key: ${{ secrets.mongodb_atlas_api_pub_key }}
          mongodb_atlas_api_pri_key: ${{ secrets.mongodb_atlas_api_pri_key }}
          mongodb_atlas_org_id: ${{ secrets.mongodb_atlas_org_id }}
          aws_account_id: ${{ secrets.aws_account_id }}
          aws_access_key: ${{ secrets.aws_access_key }}
          aws_secret_key: ${{ secrets.aws_secret_key }}
          datadog_api_key: ${{ secrets.datadog_api_key }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7

      #- name: Terraform Plan
      #  run: terraform plan -out=tfplan

      #- name: Terraform Apply
      #  run: terraform apply -auto-approve tfplan

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
        env:
          mongodb_atlas_api_pub_key: ${{ secrets.mongodb_atlas_api_pub_key }}
          mongodb_atlas_api_pri_key: ${{ secrets.mongodb_atlas_api_pri_key }}
          mongodb_atlas_org_id: ${{ secrets.mongodb_atlas_org_id }}
          aws_account_id: ${{ secrets.aws_account_id }}
          aws_access_key: ${{ secrets.aws_access_key }}
          aws_secret_key: ${{ secrets.aws_secret_key }}
          datadog_api_key: ${{ secrets.datadog_api_key }}
