name: Terraform Deploy

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      mongodb_atlas_api_pub_key: ${{ secrets.mongodb_atlas_api_pub_key }}
      mongodb_atlas_api_pri_key: ${{ secrets.mongodb_atlas_api_pri_key }}
      mongodb_atlas_org_id: ${{ secrets.mongodb_atlas_org_id }}
      aws_account_id: ${{ secrets.aws_account_id }}
      datadog_api_key: ${{ secrets.datadog_api_key }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        id: init
        run: terraform init 

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
      
            <details><summary>Show Plan</summary>
          
            \`\`\`${process.env.PLAN}\`\`\`
          
            </details>

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        #uses: hashicorp/terraform-github-actions/apply@v0.4.0
          #mongodb_atlas_api_pub_key: ${{ secrets.mongodb_atlas_api_pub_key }}
          #mongodb_atlas_api_pri_key: ${{ secrets.mongodb_atlas_api_pri_key }}
          #mongodb_atlas_org_id: ${{ secrets.mongodb_atlas_org_id }}
          #aws_account_id: ${{ secrets.aws_account_id }}
          #datadog_api_key: ${{ secrets.datadog_api_key }}


